name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Hola mundo
        run: echo ¡Hola Mundo desde ${{steps.ip.outputs.ipv4 }}!
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
      - name: Run index
        run: node main.js
