name: Trigger issues
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  trigger-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
      - name: Run js
        run: node main.js
